[package]
name = "twentyfourty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = "0.3.2"
dioxus-desktop = "0.3.0"
grid = "0.9.0"
mki = "0.2.3"
rand = "0.8"
